### ISSUE TITLE
Changes to conf or key should "notify" the OpenVPN service (optionally?)

### ISSUE THREAD

**Issue by TJM** [thias/puppet-openvpn#5]
If the configuration of the OpenVPN file has changed or if the key has changed, the service should be notified to restart.

**Comment by thias** [comment]
This definitely needs to be optional, as OpenVPN links are typically critical and not everyone will want changes to immediately restart them. Pull request welcome! :-)

**Comment by TJM** [comment]
Yea, optional for sure, but if I push down a config change (or a key change), I would expect it to restart the tunnel, rather than taking manual intervention (otherwise, what's the point of using puppet, right?) :) I probably wouldn't be pushing a config/key change to a "working" tunnel :D.  After I resolve some selinux madness wrt OpenVPN client, maybe I can get back to this.

**Comment by thias** [comment]
Pull request welcome! :-)

**Comment by FST777** [comment]
Doesn't #6 basically solve this issue?

**Comment by thias** [comment]
Yes, #6 should have basically done what was asked here.
